-- Run this script in the Supabase SQL Editor

-- 1. Create Players Table
CREATE TABLE public.players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  image TEXT NOT NULL,
  role TEXT NOT NULL,
  batting INTEGER NOT NULL,
  bowling INTEGER NOT NULL,
  average NUMERIC,
  stars INTEGER,
  objectPosition TEXT DEFAULT '50% 50%',
  scale NUMERIC DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Profiles Table (links to Supabase Auth)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT,            -- stored for in-app player search
  avatar_url TEXT,
  matches_played INTEGER DEFAULT 0,
  matches_won INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- NOTE: If the profiles table already exists, run this instead:
-- ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email TEXT;

-- 3. Create Matches Table
CREATE TABLE public.matches (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  player1_id UUID REFERENCES public.profiles(id),
  player2_id UUID REFERENCES public.profiles(id),
  winner_id UUID REFERENCES public.profiles(id),
  p1_score INTEGER DEFAULT 0,
  p2_score INTEGER DEFAULT 0,
  status TEXT DEFAULT 'in_progress', -- in_progress, completed, forfeited
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;

-- Create basic RLS policies
-- Anyone can read players
CREATE POLICY "Players are viewable by everyone" ON public.players FOR SELECT USING (true);

-- Profiles are viewable by everyone, but only updateable by the owner
CREATE POLICY "Profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Matches are viewable by everyone
CREATE POLICY "Matches are viewable by everyone" ON public.matches FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create matches" ON public.matches FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Players involved can update match" ON public.matches FOR UPDATE USING (auth.uid() = player1_id OR auth.uid() = player2_id);

-- ============================================================
-- CRITICAL: Stat-update Trigger
-- Run this separately in the Supabase SQL Editor AFTER tables exist.
-- This trigger fires whenever a row is inserted into 'matches'
-- and automatically increments matches_played for both players
-- and matches_won for the winner in the 'profiles' table.
-- ============================================================

-- Function called by the trigger
CREATE OR REPLACE FUNCTION public.update_profile_stats()
RETURNS TRIGGER AS $$
BEGIN
  -- Increment matches_played for player1
  IF NEW.player1_id IS NOT NULL THEN
    UPDATE public.profiles
    SET matches_played = matches_played + 1
    WHERE id = NEW.player1_id;
  END IF;

  -- Increment matches_played for player2
  IF NEW.player2_id IS NOT NULL THEN
    UPDATE public.profiles
    SET matches_played = matches_played + 1
    WHERE id = NEW.player2_id;
  END IF;

  -- Increment matches_won for the winner
  IF NEW.winner_id IS NOT NULL THEN
    UPDATE public.profiles
    SET matches_won = matches_won + 1
    WHERE id = NEW.winner_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- The trigger that fires after each INSERT on matches
CREATE TRIGGER on_match_inserted
AFTER INSERT ON public.matches
FOR EACH ROW
EXECUTE FUNCTION public.update_profile_stats();
